name: michael_in_3d
favicon: null
layout_spectrum: 0.6361536295153201
typography_spectrum: 0.6191255799494684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.005361781921237707
  lightness: 0.7360428711399436
  saturation: 0.7703561121597886
  rhythmicContrast: 0.7071919231675565
purpose: []
